In [19]:
import numpy as np
import pandas as pd

# ----------------------------
# Functions
# ----------------------------

def research(x):
    return 200_000 * np.log(1 + x) / np.log(101)

def scale(y):
    return 7 * y / 100

def get_speed_multiplier(my_z, others):
    all_speeds = others + [my_z]
    unique_sorted = sorted(set(all_speeds), reverse=True)

    rank = unique_sorted.index(my_z) + 1
    n = len(unique_sorted)

    if n == 1:
        return 0.9

    return 0.9 - (rank - 1) * (0.8 / (n - 1))


def pnl(x, y, z, others):
    speed_mult = get_speed_multiplier(z, others)
    gross = research(x) * scale(y) * speed_mult
    cost = x + y + z
    return gross - cost


# ----------------------------
# Grid search
# ----------------------------

def run_grid(others):
    results = []

    for x in range(101):
        for y in range(101 - x):
            for z in range(101 - x - y):
                val = pnl(x, y, z, others)
                results.append((x, y, z, x+y+z, val))

    df = pd.DataFrame(results, columns=[
        "research", "scale", "speed", "budget_used", "pnl"
    ])
    return df.sort_values("pnl", ascending=False).reset_index(drop=True)


# ----------------------------
# Try multiple scenarios
# ----------------------------

scenarios = {
    "balanced_players": [20, 40, 50, 60, 70, 30, 45],
    "low_speed_players": [10, 20, 30, 25, 15, 35, 40],
    "high_speed_players": [60, 70, 80, 90, 75, 65, 85],
}

all_results = []

for name, others in scenarios.items():
    df = run_grid(others)
    df["scenario"] = name
    print(f"\n=== Top results for {name} ===")
    print(df.head(10))
    all_results.append(df.head(50))  # keep top 50 for merging

# ----------------------------
# Combine for robustness
# ----------------------------

combined = pd.concat(all_results)

grouped = combined.groupby(["research", "scale", "speed", "budget_used"]).agg(
    avg_pnl=("pnl", "mean"),
    min_pnl=("pnl", "min")
).reset_index()

print("\n=== Robust (best avg PnL) ===")
print(grouped.sort_values("avg_pnl", ascending=False).head(20))

print("\n=== Robust (best worst-case PnL) ===")
print(grouped.sort_values("min_pnl", ascending=False).head(20))

=== Top results for balanced_players ===
   research  scale  speed  budget_used            pnl          scenario
0        13     36     51          100  193406.756125  balanced_players
1        12     37     51          100  193197.094468  balanced_players
2        14     35     51          100  192949.891744  balanced_players
3        11     38     51          100  192226.213815  balanced_players
4        15     34     51          100  191903.513753  balanced_players
5        10     39     51          100  190375.720796  balanced_players
6        16     33     51          100  190331.165583  balanced_players
7        17     32     51          100  188285.941733  balanced_players
8        13     35     51           99  188032.568455  balanced_players
9        13     35     52          100  188031.568455  balanced_players

=== Top results for low_speed_players ===
   research  scale  speed  budget_used            pnl           scenario
0        15     45     40          100  340532.015951  low_speed_players
1        16     44     40          100  340245.061892  low_speed_players
2        14     46     40          100  339996.405030  low_speed_players
3        17     43     40          100  339220.157017  low_speed_players
4        13     47     40          100  338536.823219  low_speed_players
5        18     42     40          100  337528.692921  low_speed_players
6        12     48     40          100  336030.197626  low_speed_players
7        19     41     40          100  335231.501500  low_speed_players
8        15     44     40           99  332963.415597  low_speed_players
9        15     44     41          100  332962.415597  low_speed_players

=== Top results for high_speed_players ===
   research  scale  speed  budget_used           pnl            scenario
0        23     77      0          100  74132.991676  high_speed_players
1        24     76      0          100  74110.063749  high_speed_players
2        22     78      0          100  74090.038403  high_speed_players
3        25     75      0          100  74025.937826  high_speed_players
4        21     79      0          100  73975.919381  high_speed_players
5        26     74      0          100  73884.785028  high_speed_players
6        20     80      0          100  73784.638934  high_speed_players
7        27     73      0          100  73690.337586  high_speed_players
8        19     81      0          100  73509.353988  high_speed_players
9        28     72      0          100  73445.949325  high_speed_players

=== Robust (best avg PnL) ===
     research  scale  speed  budget_used        avg_pnl        min_pnl
64         15     45     40          100  340532.015951  340532.015951
75         16     44     40          100  340245.061892  340245.061892
53         14     46     40          100  339996.405030  339996.405030
85         17     43     40          100  339220.157017  339220.157017
42         13     47     40          100  338536.823219  338536.823219
91         18     42     40          100  337528.692921  337528.692921
27         12     48     40          100  336030.197626  336030.197626
98         19     41     40          100  335231.501500  335231.501500
62         15     44     40           99  332963.415597  332963.415597
63         15     44     41          100  332962.415597  332962.415597
51         14     45     40           99  332604.004921  332604.004921
52         14     45     41          100  332603.004921  332603.004921
73         16     43     40           99  332510.946849  332510.946849
74         16     43     41          100  332509.946849  332509.946849
104        20     40     40          100  332380.875204  332380.875204
16         11     49     40          100  332324.984349  332324.984349
40         13     46     40           99  331332.784428  331332.784428
41         13     46     41          100  331331.784428  331331.784428
83         17     42     40           99  331329.990575  331329.990575
84         17     42     41          100  331328.990575  331328.990575

=== Robust (best worst-case PnL) ===
     research  scale  speed  budget_used        avg_pnl        min_pnl
64         15     45     40          100  340532.015951  340532.015951
75         16     44     40          100  340245.061892  340245.061892
53         14     46     40          100  339996.405030  339996.405030
85         17     43     40          100  339220.157017  339220.157017
42         13     47     40          100  338536.823219  338536.823219
91         18     42     40          100  337528.692921  337528.692921
27         12     48     40          100  336030.197626  336030.197626
98         19     41     40          100  335231.501500  335231.501500
62         15     44     40           99  332963.415597  332963.415597
63         15     44     41          100  332962.415597  332962.415597
51         14     45     40           99  332604.004921  332604.004921
52         14     45     41          100  332603.004921  332603.004921
73         16     43     40           99  332510.946849  332510.946849
74         16     43     41          100  332509.946849  332509.946849
104        20     40     40          100  332380.875204  332380.875204
16         11     49     40          100  332324.984349  332324.984349
40         13     46     40           99  331332.784428  331332.784428
41         13     46     41          100  331331.784428  331331.784428
83         17     42     40           99  331329.990575  331329.990575
84         17     42     41          100  331328.990575  331328.990575

np.float64(-4.61512051684126)

In [13]:
def func_log(x):
    
    return 200000 * (np.log(1+x) / np.log(101))

func_log(0)

np.float64(0.0)

In [15]:
func_log(10)

np.float64(103914.74129648815)

In [16]:
func_log(20)

np.float64(131936.85523979316)

In [17]:
func_log(30)

np.float64(148814.62756840335)

In [20]:
func_log(50)

np.float64(170388.86063219846)

In [12]:
func_log(5)

np.float64(0.38823676709842325)

In [51]:
b_list = [x for x in range(50,75)]

def generate_pairs(b_list):
    
    results = []
    
    for b in b_list:
        
        for x in range(b+1):
            
            y = b - x
            
            r = generate_research(y)
            s = generate_scale(x)
            
            #print(f"b: {b}, x: {x}, y: {y}")
            
            mul = s * r
            #print(f"mul: {mul}")
            
            results.append((b, x, y, mul))
    
    results_df = pd.DataFrame(results, columns=["b", "x", "y", "mul"])
    return results_df
            
def generate_research(a):
    return 200000 * (np.log(1+a) / np.log(101))

def generate_scale(a):
    return 7 * a / 100

In [52]:
results_df = generate_pairs(b_list)
results_df

       b   x   y            mul
0     50   0  50       0.000000
1     50   1  49   11867.148837
2     50   2  48   23611.727570
3     50   3  47   35229.945104
4     50   4  46   46717.797490
...   ..  ..  ..            ...
1570  74  70   4  341756.872530
1571  74  71   3  298578.680649
1572  74  72   2  239950.654146
1573  74  73   1  153494.673855
1574  74  74   0       0.000000

[1575 rows x 4 columns]

In [53]:
results_df.sort_values("mul", ascending=False)

       b   x   y            mul
1556  74  56  18  500190.656180
1555  74  55  19  499816.601152
1557  74  57  17  499773.874677
1554  74  54  20  498721.312806
1558  74  58  16  498485.191660
...   ..  ..  ..            ...
869   64  64   0       0.000000
805   64   0  64       0.000000
804   63  63   0       0.000000
741   63   0  63       0.000000
1574  74  74   0       0.000000

[1575 rows x 4 columns]

In [59]:
best_per_budget = results_df.loc[results_df.groupby("b")["mul"].idxmax()]

print(best_per_budget[["b", "x", "y", "mul"]].to_string(index=False))
print()
print(f"Research range: {best_per_budget['y'].min()} – {best_per_budget['y'].max()}")
print(f"Scale range:    {best_per_budget['x'].min()} – {best_per_budget['x'].max()}")

 b  x  y           mul
50 37 13 296207.150334
51 38 13 304212.748991
52 39 13 312218.347649
53 39 14 320380.671405
54 40 14 328595.560416
55 41 14 336810.449426
56 42 14 345025.338436
57 42 15 353248.016542
58 43 15 361658.683603
59 44 15 370069.350663
60 45 15 378480.017724
61 46 15 386890.684784
62 46 16 395350.324420
63 47 16 403944.896690
64 48 16 412539.468960
65 49 16 421134.041230
66 50 16 429728.613500
67 50 17 438398.135681
68 51 17 447166.098395
69 52 17 455934.061108
70 53 17 464702.023822
71 54 17 473469.986536
72 54 18 482326.704173
73 55 18 491258.680176
74 56 18 500190.656180

Research range: 13 – 18
Scale range:    37 – 56

In [58]:
x

       b   x   y            mul
1556  74  56  18  500190.656180
1555  74  55  19  499816.601152
1557  74  57  17  499773.874677
1554  74  54  20  498721.312806
1558  74  58  16  498485.191660
...   ..  ..  ..            ...
1503  74   3  71   38919.888732
1502  74   2  72   26030.276764
1501  74   1  73   13056.411222
1500  74   0  74       0.000000
1574  74  74   0       0.000000

[75 rows x 4 columns]

In [44]:
results_df[results_df["b"] == 50].sort_values("mul", ascending=False)

     b   x   y            mul
37  50  37  13  296207.150334
36  50  36  14  295736.004374
38  50  38  12  295670.081245
35  50  35  15  294373.347118
39  50  39  11  293981.278676
34  50  34  16  292215.457180
40  50  40  10  290961.275630
33  50  33  17  289342.769550
41  50  41   9  286381.219852
32  50  32  18  285823.232103
31  50  31  19  281714.811559
42  50  42   8  279942.429837
30  50  30  20  277067.396004
29  50  29  21  271924.261021
43  50  43   7  271244.012702
28  50  28  22  266323.214780
27  50  27  23  260297.503280
44  50  44   6  259729.003272
26  50  26  24  253876.533880
25  50  25  25  247086.459421
45  50  45   5  244589.163272
24  50  24  26  239950.654146
23  50  23  27  232490.104724
22  50  22  28  224723.734050
46  50  46   4  224583.087663
21  50  21  29  216668.671286
20  50  20  30  208340.478596
19  50  19  31  199753.342688
47  50  47   3  197650.675922
18  50  18  32  190920.237570
17  50  17  33  181853.063597
16  50  16  34  172562.766859
15  50  15  35  163059.442181
48  50  48   2  159967.102764
14  50  14  36  153352.422390
13  50  13  37  143450.355988
12  50  12  38  133361.275031
11  50  11  39  123092.654647
10  50  10  40  112651.465426
49  50  49   1  103030.671491
9   50   9  41  102044.219687
8   50   8  42   91277.012468
7   50   7  43   80355.557947
6   50   6  44   69285.221908
5   50   5  45   58071.050751
4   50   4  46   46717.797490
3   50   3  47   35229.945104
2   50   2  48   23611.727570
1   50   1  49   11867.148837
0   50   0  50       0.000000
50  50  50   0       0.000000

In [45]:
results_df[results_df["b"] == 55].sort_values("mul", ascending=False)

      b   x   y            mul
92   55  41  14  336810.449426
91   55  40  15  336426.682421
93   55  42  13  336235.143622
90   55  39  16  335188.318530
94   55  43  12  334574.039303
89   55  38  17  333182.583118
95   55  44  11  331671.186198
88   55  37  18  330483.112119
96   55  45  10  327331.435084
87   55  36  19  327152.684391
86   55  35  20  323245.295337
97   55  46   9  321305.758859
85   55  34  21  318807.754300
84   55  33  22  313880.931705
98   55  47   8  313268.909579
83   55  32  23  308500.744629
99   55  48   7  302784.014179
82   55  31  24  302698.944241
81   55  30  25  296503.751305
80   55  29  26  289940.373759
100  55  49   6  289243.662734
79   55  28  27  283031.431838
78   55  27  28  275797.309971
101  55  50   5  271765.736969
77   55  26  29  268256.450164
76   55  25  30  260425.598245
75   55  24  31  252320.011816
102  55  51   4  248994.292843
74   55  23  32  243953.636895
73   55  22  33  235339.258773
72   55  21  34  226488.631502
103  55  52   3  218677.343574
71   55  20  35  217412.589575
70   55  19  36  208121.144672
69   55  18  37  198623.569830
68   55  17  38  188928.472961
67   55  16  39  179043.861305
104  55  53   2  176630.342635
66   55  15  40  168977.198139
65   55  14  41  158735.452847
64   55  13  42  148325.145261
63   55  12  43  137752.385052
62   55  11  44  127022.906831
61   55  10  45  116142.101501
105  55  54   1  113544.005317
60   55   9  46  105115.044352
59   55   8  47   93946.520278
58   55   7  48   82641.046496
57   55   6  49   71202.893025
56   55   5  50   59636.101221
55   55   4  51   47944.500568
54   55   3  52   36131.723919
53   55   2  53   24201.221376
52   55   1  54   12156.272927
51   55   0  55       0.000000
106  55  55   0       0.000000

In [46]:
results_df[results_df["b"] == 60].sort_values("mul", ascending=False)

      b   x   y            mul
152  60  45  15  378480.017724
151  60  44  16  378161.179880
153  60  46  14  377884.894478
150  60  43  17  377022.396686
154  60  47  13  376263.136911
..   ..  ..  ..            ...
110  60   3  57   36952.145848
109  60   2  58   24738.476062
108  60   1  59   12420.222541
107  60   0  60       0.000000
167  60  60   0       0.000000

[61 rows x 4 columns]

In [47]:
results_df[results_df["b"] == 65].sort_values("mul", ascending=False)

      b   x   y            mul
217  65  49  16  421134.041230
216  65  48  17  420862.210254
218  65  50  15  420533.353026
215  65  47  18  419802.872151
219  65  51  14  418959.339530
..   ..  ..  ..            ...
171  65   3  62   37704.683523
170  65   2  63   25232.001182
169  65   1  64   12663.032648
168  65   0  65       0.000000
233  65  65   0       0.000000

[66 rows x 4 columns]

In [36]:
def res_scale(x, y):
    
    r = generate_research(x)
    s = generate_scale(y)
    
    mul = s * r
    return mul

In [37]:
res_scale(20, 40)

np.float64(369423.19467142085)

In [38]:
res_scale(25, 35)

np.float64(345921.0431893989)

In [39]:
res_scale(30, 30)

np.float64(312510.71789364703)

In [40]:
res_scale(15, 45)

np.float64(378480.01772369357)

In [48]:
res_scale(33, 37)

np.float64(395797.84430015145)

In [50]:
res_scale(17, 53)

np.float64(464702.0238220836)